name: Update Metrics

on:
 schedule:
  - cron: "0 * * * *" # Update every hour

jobs:
 update_metrics:
  runs-on: ubuntu-latest

  steps:
   - name: Check out repository
     uses: actions/checkout@v2.3.4

   - name: Set up Node.js
     uses: actions/setup-node@v2.4.0
     with:
      node-version: 16

   - name: Install dependencies
     run: npm ci

   - name: Generate Metrics
     run: npx metrics --template classic --output README.md

   - name: Commit and push changes
     run: |
      git config --local user.email "actions@github.com"
      git config --local user.name "GitHub Actions"
      git add README.md
      git commit -m "Update Metrics" -a || true
      git push
